# Site settings
title: Azure Enterprise Toolkit
description: Professional Azure automation with 124+ PowerShell scripts for enterprise cloud management
baseurl: "/Azure-Enterprise-Toolkit"
url: "https://wesellis.github.io"

# Author settings
author:
  name: Wesley Ellis
  email: wes@wesellis.com
  github: wesellis
  linkedin: wesleyellis
  website: https://wesellis.com

# Repository settings
repository: wesellis/Azure-Enterprise-Toolkit
branch: main

# GitHub Pages settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - .git
  - .github

# Include files
include:
  - _redirects

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections (for future use)
collections:
  scripts:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "scripts"
    values:
      layout: "script"

# SEO settings
lang: en_US
twitter:
  username: wesleyellis
  card: summary_large_image

logo: /assets/images/logo.png

social:
  name: Wesley Ellis
  links:
    - https://github.com/wesellis
    - https://linkedin.com/in/wesleyellis
    - https://wesellis.com

# Google Analytics (uncomment and add your tracking ID)
# google_analytics: G-XXXXXXXXXX

# Theme settings (using default GitHub Pages theme)
theme: minima

# Custom variables
toolkit:
  version: "2.0"
  script_count: "124+"
  last_updated: "2025-06-16"
  categories:
    - name: "Compute Management"
      count: 18
      icon: "fas fa-server"
    - name: "Network Security"
      count: 22
      icon: "fas fa-network-wired"
    - name: "Data Storage"
      count: 16
      icon: "fas fa-database"
    - name: "Monitoring Operations"
      count: 14
      icon: "fas fa-chart-bar"
    - name: "Identity Governance"
      count: 12
      icon: "fas fa-user-shield"
    - name: "App Development"
      count: 15
      icon: "fas fa-mobile-alt"
    - name: "General Utilities"
      count: 20
      icon: "fas fa-tools"
    - name: "Cross-Platform Tools"
      count: 7
      icon: "fas fa-laptop-code"
