name: PowerShell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install PowerShell modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module -Name PSScriptAnalyzer -Force
        Install-Module -Name Pester -Force
    
    - name: Validate PowerShell scripts
      shell: pwsh
      run: |
        Write-Host "Validating PowerShell script syntax..."
        $scripts = Get-ChildItem -Path . -Recurse -Include *.ps1
        Write-Host "Found $($scripts.Count) PowerShell scripts"
        $errors = 0
        foreach ($script in $scripts) {
          try {
            $null = [System.Management.Automation.PSParser]::Tokenize((Get-Content $script.FullName -Raw), [ref]$null)
          } catch {
            Write-Warning "Syntax error in $($script.Name)"
            $errors++
          }
        }
        if ($errors -eq 0) {
          Write-Host "✅ All scripts have valid PowerShell syntax!" -ForegroundColor Green
        } else {
          Write-Host "⚠️ Found $errors scripts with syntax issues (non-blocking)" -ForegroundColor Yellow
        }
    
    - name: Count scripts
      shell: pwsh
      run: |
        $count = (Get-ChildItem -Path . -Recurse -Include *.ps1).Count
        Write-Host "📊 Repository contains $count PowerShell scripts"